# Generated by Django 3.1.3 on 2020-12-20 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import session_manager.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('registration_source', models.CharField(choices=[('website', 'website'), ('invitation', 'invitation')], max_length=25)),
                ('post_process_status', models.CharField(choices=[('invitation processed', 'invitation processed'), ('not processed', 'not processed'), ('registration processed', 'registration processed')], default='not processed', max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(max_length=50)),
                ('to_email', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64)),
                ('token_type', models.CharField(choices=[('reset', 'reset'), ('login', 'login'), ('registration', 'registration'), ('invitation', 'invitation')], max_length=20)),
                ('expiration', models.DateTimeField(blank=True, default=session_manager.utils.TimeDiff.fourtyeighthoursfromnow)),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_manager.appuser')),
            ],
        ),
    ]
