# Generated by Django 3.1.3 on 2020-12-19 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('spending_limit', models.IntegerField(blank=True, null=True)),
                ('exchange_in_person', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('participants_notified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='session_manager.appuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.TextField(blank=True, null=True)),
                ('dislikes', models.TextField(blank=True, null=True)),
                ('allergies_or_sensitivities', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_manager.appuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GiftExchangeParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_likes', models.TextField(blank=True, null=True)),
                ('_dislikes', models.TextField(blank=True, null=True)),
                ('_allergies_or_sensitivities', models.TextField(blank=True, null=True)),
                ('_shipping_address', models.TextField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('inactive', 'inactive'), ('invited', 'invited'), ('declined', 'declined')], default='active', max_length=10)),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_manager.appuser')),
                ('giftexchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifterator.giftexchange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftexchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifterator.giftexchange')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftexchange_giver', to='gifterator.giftexchangeparticipant')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giftexchange_reciever', to='gifterator.giftexchangeparticipant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
