# Generated by Django 3.1.3 on 2020-12-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager', '0001_initial'),
        ('gifterator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefault',
            name='appuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='session_manager.appuser'),
        ),
    ]
