# Generated by Django 3.1.3 on 2020-12-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifterator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeparticipant',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
