# Generated by Django 3.1.3 on 2020-12-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifterator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftexchangeparticipant',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('inactive', 'inactive'), ('invited', 'invited'), ('declined', 'declined')], default='active', max_length=10),
        ),
    ]
