# Generated by Django 3.1.3 on 2020-12-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager', '0002_auto_20201220_2212'),
        ('gifterator', '0003_exchangeparticipant_email_last_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftexchange',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='giftexchange',
            unique_together={('title', 'created_by')},
        ),
    ]
