# Generated by Django 3.1.3 on 2020-12-22 19:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager', '0002_auto_20201220_2212'),
        ('gifterator', '0004_add_email_sent_metadata_to_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('nickname', models.CharField(max_length=250)),
                ('is_default', models.BooleanField(default=False)),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session_manager.appuser')),
            ],
            options={
                'unique_together': {('appuser', 'nickname')},
            },
        ),
        migrations.CreateModel(
            name='GiftListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('web_link', models.URLField(blank=True, null=True)),
                ('nickname', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('giftlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifterator.giftlist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeGiftListLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifterator.giftlist')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifterator.exchangeparticipant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
