# Generated by Django 3.1.3 on 2020-12-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifterator', '0005_exchangegiftlistlink_giftlist_giftlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftlistitem',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
