# Generated by Django 3.1.3 on 2020-12-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifterator', '0006_giftlistitem_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftlistitem',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
